[server]
headless = true
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
base = "light"

[logger]
level = "error"